name: Go CI

on:
  push:
    branches: '**'

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Test Go Code
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Install test dependencies
      run: go install github.com/jstemmer/go-junit-report@latest

    - name: Test
      run: for i in ./*; do (cd "$i"; go test -v 2>&1 ./...); done | go-junit-report -set-exit-code > report.xml

    - name: Publish test Summary
      uses: test-summary/action@v2
      with:
        paths: report.xml            
      if: always()

  Release:
    needs: Test
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.67.0
      id: tag-version
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Create Release
      run: GOPROXY=proxy.golang.org go list -m github.com/michael-ryan/mikelib@${{ steps.tag-version.outputs.new_tag }}
