# This workflow will build and publish a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  TestAndRelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Install test dependencies
      run: go install github.com/jstemmer/go-junit-report@latest

    - name: Test
      run: go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: report.xml            
      if: always()

    # https://github.com/marketplace/actions/tag-version
    - name: tag-version
      uses: juliansangillo/tag-version@v1.5
      id: tag-version
      if: github.event_name == 'push'

    - name: Create Release
      run: go mod tidy; echo "${{ steps.tag-version.outputs.revision }}" #GOPROXY=proxy.golang.org go list -m github.com/michael-ryan/mikelib@
